
name: 构建并推送 Docker 镜像

on:
  schedule:
  - cron: '0 7 * * *'
  push:
    branches:
      - master

env:
  TZ: Asia/Shanghai 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 下载并解压上游源代码
        run: |
          curl -OL https://github.com/sangxuesheng/lsky-pro-Docker/archive/refs/tags/1.0.zip
          unzip *.zip
          mv ./lsky-pro-master/* ./
          mv ./lsky-pro-master/.env.example ./
          rm -rf master.zip lsky-pro-master
      
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
        
      - name: 复制 .env 文件
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: 安装依赖
        run: composer install

      - name: 登录到 DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: 构建并推送镜像
        run: |
          docker build -t halcyonazure/lsky-pro-docker:latest .
          docker push halcyonazure/lsky-pro-docker:latest
